# Generated by Django 4.2.24 on 2025-09-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asistira_gobernador',
            field=models.BooleanField(default=False, verbose_name='¿Asistirá el Gobernador?'),
        ),
    ]
