# Generated by Django 4.2.24 on 2025-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_asistira_gobernador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asistira_gobernador',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='¿Asistirá el Gobernador?'),
        ),
    ]
