# Generated by Django 4.2.24 on 2025-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_asistira_gobernador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asistira_gobernador',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=False, null=True, verbose_name='¿Asistirá el Gobernador?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar_evento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número del Documento'),
        ),
    ]
