# Generated by Django 4.2.24 on 2025-09-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_asistira_gobernador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('cve_dep', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave de la Dependencia')),
                ('nom_dep', models.CharField(max_length=255, verbose_name='Nombre de la Dependencia')),
                ('titular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular de la Dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['nom_dep'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre_dependencia',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='titular_dependencia',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.dependencia', verbose_name='Dependencia'),
        ),
    ]
