# Generated by Django 4.2.24 on 2025-09-22 18:29

from django.db import migrations

def populate_dependencias(apps, schema_editor):
    Dependencia = apps.get_model('eventos', 'Dependencia')
    dependencias_data = [
        (1, 'Secretaría General de Gobierno y Mediación'),
        (2, 'Secretaría de Finanzas'),
        (3, 'Secretaría Anticorrupción y Buen Gobierno'),
        (4, 'Secretaría de Economía y del Trabajo'),
        (5, 'Secretaría de la Mujer e Igualdad de Género'),
        (6, 'Secretaría de Protección Civil'),
        (7, 'Secretaría de Infraestructura'),
        (8, 'Secretaría de Medio Ambiente e Historia Natural'),
        (9, 'Secretaría de Humanismo'),
        (10, 'Secretaría de Agricultura, Ganadería y Pesca'),
        (11, 'Secretaría de Turismo'),
        (12, 'Secretaría para el Desarrollo Sustentable de los Pueblos Indígenas'),
        (13, 'Secretario de Salud '),
        (14, 'Secretaría de Educación'),
        (15, 'Secretaría de Seguridad del Pueblo'),
        (16, 'Secretaría de Movilidad y Transportes'),
        (17, 'Instituto de la Consejería Jurídica del Gobierno del Estado'),
        (18, 'Coordinación de Asesores y Proyectos Estratégicos '),
        (19, 'Secretariado Ejecutivo del Sistema Estatal de Seguridad Pública'),
        (20, 'Sistema para el Desarrollo Integral de la Familia del Estado de Chiapas'),
        (21, 'Instituto de la Infraestructura Física Educativa del Estado de Chiapas.'),
        (23, 'Consejo Estatal para las Culturas y las Artes de Chiapas'),
        (24, 'Instituto Chiapaneco de Educación para Jóvenes y Adultos'),
        (25, 'Instituto de Comunicación Social y Relaciones Públicas del Estado de Chiapas'),
        (26, 'Instituto Casa de las Artesanías de Chiapas'),
        (27, 'Instituto de Seguridad Social de los Trabajadores del Estado de Chiapas'),
        (28, 'Instituto del Café de Chiapas'),
        (29, 'Aeroportuario de la Sociedad Operadora del Aeropuerto Internacional Ángel Albino Corzo, S.A DE C.V.'),
        (30, 'Sistema Chiapaneco de Radio, Televisión y Cinematografía'),
        (31, 'Oficina de Convenciones y Visitantes del Estado de Chiapas'),
        (32, 'Talleres Gráficos de Chiapas'),
        (33, 'Centro Estatal de Control de Confianza Certificado'),
        (34, 'Conalep Chiapas'),
        (35, 'Colegio de Bachilleres de Chiapas'),
        (37, 'Instituto de la Vivienda'),
        (38, 'Instituto Estatal del Agua'),
        (39, 'Instituto de Evaluación, Profesionalización y Promoción Docente de Chiapas.'),
        (40, 'Coordinación Estatal para el Mejoramiento del Zoológico "Miguel Álvarez del Toro"'),
        (41, 'Instituto de Formación Humana y Productiva del Estado de Chiapas'),
        (42, 'Colegio de Estudios Científicos y Tecnológicos del Estado de Chiapas'),
        (43, 'Instituto del Deporte del Estado de Chiapas'),
        (44, 'Sociedad Operadora Torre Chiapas'),
        (45, 'Centro Estatal de Prevención Social de la Violencia y Participación Ciudadana'),
        (46, 'Instituto de Protección Social y Beneficencia Pública del Estado de Chiapas'),
        (47, 'Instituto de la Juventud del Estado de Chiapas'),
        (58, 'Agencia Digital Tecnológica del Estado de Chiapas'),
        (96, 'Universidad Autónoma de Chiapas'),
        (180, 'Fiscalía General del Estado de Chiapas'),
        (181, 'Instituto del Patrimonio del Estado'),
        (185, 'Comisión Estatal de Búsqueda de Personas'),
        (186, 'Tribunal Superior de Justicia y Consejo de la Judicatura del Estado de Chiapas'),
        (229, 'Comisión Ejecutiva Estatal de Atención a Víctimas'),
        (233, 'Universidad de Ciencias y Artes de Chiapas'),
        (234, 'Congreso del Estado de Chiapas'),
        (237, 'Oficina de la Gubernatura'),
        (243, 'Secretaría de la Frontera Sur ')
    ]

    for cve, nom in dependencias_data:
        Dependencia.objects.get_or_create(cve_dep=cve, defaults={'nom_dep': nom})

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_dependencia_remove_customuser_nombre_dependencia_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_dependencias),
    ]
