# Generated by Django 4.2.24 on 2025-09-22 19:02

from django.db import migrations

def update_dependencia_titulares(apps, schema_editor):
    Dependencia = apps.get_model('eventos', 'Dependencia')
    titulares_data = [
        (1, 'Lic. Juan Pérez'),
        (2, 'Lic.Manuel Francisco Antonio Pariente Gavito.'),
        (3, 'Mtra. Ana Laura Romero Basurto.'),
        (4, 'Lic. Luis Pedrero González.'),
        (5, 'Lic. Dulce María Rodríguez Ovando.'),
        (6, 'Lic. Luis Mauricio Cordero Rodríguez.'),
        (7, 'Mtra. Anakaren Gómez Zuart.'),
        (8, 'Mtra. Magdalena Torres Abarca.'),
        (9, 'Dr. Francisco Chacón Sánchez.'),
        (10, 'MVZ. Marco Antonio Barba Arrocha.'),
        (11, 'Lic. María Eugenia Culebro Pérez.'),
        (12, 'Lic. Leticia Méndez Intzin.'),
        (13, 'Dr. Omar Gómez Cruz.'),
        (14, 'Dr. Roger Adrián Mandujano Ayala.'),
        (15, 'C.P.A. Dr. Óscar Alberto Aparicio Avendaño.'),
        (16, 'Lic. Albania González Pólito.'),
        (17, 'Dr. Guillermo Nieto Arreola.'),
        (18, 'Dr. Juan Carlos López Aranda.'),
        (19, 'Dr. José Domingo Bezares Vázquez.'),
        (20, 'Mtra. Ana Isabel Granda González.'),
        (21, 'Lic. Carlos Ildefonso Jiménez Trujillo.'),
        (23, 'Mtra. Angélica Altuzar Constantino. '),
        (24, 'Lic. Sergio David Molina Gómez.'),
        (25, 'Lic. José Luis Sánchez García.'),
        (26, 'Lic. Marisol Urbina Matus.'),
        (27, 'Dr. Armando Barrios Fierro.'),
        (28, 'Lic. Jorge Baldemar Utrilla Robles.'),
        (29, 'Lic. Antonio Noguera Zurita.'),
        (30, 'Lic. Mario Escobar Gálvez.'),
        (31, 'Lic. Víctor Manuel Bermúdez Hernández.'),
        (32, 'Lic. Rubén Alberto Moguel Nuricumbo.'),
        (33, 'Mtro. José Alonso Llaven Villarreal.'),
        (34, 'Mtro. Leonardo Omar León Alcázar'),
        (35, 'Mtro. Miguel Prado de los Santos'),
        (37, 'Ing. Fernando Farro José'),
        (38, 'Dra. Karina Montesinos Cárdenas'),
        (39, 'Lic. René Velasquez Santiago.'),
        (40, 'MVZ. Joe Miceli Hernández'),
        (41, 'Dr. César Espinosa Morales'),
        (42, 'Mtro. Luis Guadalupe Morales Ángeles.'),
        (43, 'Lic. Adonaí Sánchez Osorio.'),
        (44, 'Pendiente'),
        (45, 'Lic. Yolanda María Alfaro Pérez'),
        (46, 'Pendiente'),
        (47, 'Mtro. Edgar Alejandro Abarca Palma.'),
        (53, 'Mtro. Jorge Luis Llaven Abarca'),
        (54, 'Pendiente.'),
        (55, 'Dr. Oswaldo Chacón Rojas'),
        (58, 'Lic. Alexander Jovani Salazar Ruiz'),
        (181, 'Pendiente'),
        (229, 'Pendiente'),
        (232, 'Dr. Juan Carlos Moreno Guillén'),
        (233, 'Mtro. Juan José Solorzano Marcial'),
        (234, 'Dip. Luis Ignacio Avendaño Bermúdez.'),
        (235, 'Mtro. Fernando Octavio Bermúdez Velasco'),
        (236, 'Dra. María Malia Guadalupe Toriello Elorza.'),
    ]

    for cve, nom_titular in titulares_data:
        try:
            dependencia = Dependencia.objects.get(cve_dep=cve)
            dependencia.titular = nom_titular
            dependencia.save()
        except Dependencia.DoesNotExist:
            print(f"Advertencia: No se encontró la dependencia con cve_dep={cve}")

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_populate_dependencias'),
    ]

    operations = [
        migrations.RunPython(update_dependencia_titulares),
    ]