# Generated by Django 4.2.24 on 2025-09-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_update_dependencia_titulares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('cve_titular', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave del Titular')),
                ('nom_titular', models.CharField(max_length=255, verbose_name='Nombre del Titular')),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
                'ordering': ['nom_titular'],
            },
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='titular',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='old_titular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular de la Dependencia (old)'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='titular_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.titular', verbose_name='Titular de la Dependencia'),
        ),
    ]
