# Generated by Django 4.2.24 on 2025-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_populate_dependencia_titular_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cve_mun', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave del Municipio')),
                ('nom_mun', models.CharField(max_length=255, verbose_name='Nombre del Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nom_mun'],
            },
        ),
    ]
