# Generated by Django 4.2.24 on 2025-09-22 22:05

from django.db import migrations

def populate_municipios(apps, schema_editor):
    """
    Poblar el modelo Municipio con los datos de los municipios de Chiapas.
    """
    Municipio = apps.get_model('eventos', 'Municipio')
    db_alias = schema_editor.connection.alias

    municipios_data = [
        (1, 'Acacoyagua'), (2, 'Acala'), (3, 'Acapetahua'), (4, 'Altamirano'),
        (5, 'Amatán'), (6, 'Amatenango de la Frontera'), (7, 'Amatenango del Valle'),
        (8, 'Angel Albino Corzo'), (9, 'Arriaga'), (10, 'Bejucal de Ocampo'),
        (11, 'Bella Vista'), (12, 'Berriozábal'), (13, 'Bochil'), (14, 'El Bosque'),
        (15, 'Cacahoatán'), (16, 'Catazajá'), (17, 'Cintalapa'), (18, 'Coapilla'),
        (19, 'Comitán de Domínguez'), (20, 'La Concordia'), (21, 'Copainalá'),
        (22, 'Chalchihuitán'), (23, 'Chamula'), (24, 'Chanal'), (25, 'Chapultenango'),
        (26, 'Chenalhó'), (27, 'Chiapa de Corzo'), (28, 'Chiapilla'), (29, 'Chicoasén'),
        (30, 'Chicomuselo'), (31, 'Chilón'), (32, 'Escuintla'), (33, 'Francisco León'),
        (34, 'Frontera Comalapa'), (35, 'Frontera Hidalgo'), (36, 'La Grandeza'),
        (37, 'Huehuetán'), (38, 'Huixtán'), (39, 'Huitiupán'), (40, 'Huixtla'),
        (41, 'La Independencia'), (42, 'Ixhuatán'), (43, 'Ixtacomitán'), (44, 'Ixtapa'),
        (45, 'Ixtapangajoya'), (46, 'Jiquipilas'), (47, 'Jitotol'), (48, 'Juárez'),
        (49, 'Larráinzar'), (50, 'La Libertad'), (51, 'Mapastepec'),
        (52, 'Las Margaritas'), (53, 'Mazapa de Madero'), (54, 'Mazatán'),
        (55, 'Metapa'), (56, 'Mitontic'), (57, 'Motozintla'), (58, 'Nicolás Ruíz'),
        (59, 'Ocosingo'), (60, 'Ocotepec'), (61, 'Ocozocoautla de Espinosa'),
        (62, 'Ostuacán'), (63, 'Osumacinta'), (64, 'Oxchuc'), (65, 'Palenque'),
        (66, 'Pantelhó'), (67, 'Pantepec'), (68, 'Pichucalco'), (69, 'Pijijiapan'),
        (70, 'El Porvenir'), (71, 'Villa Comaltitlán'), (72, 'Pueblo Nuevo Solistahuacán'),
        (73, 'Rayón'), (74, 'Reforma'), (75, 'Las Rosas'), (76, 'Sabanilla'),
        (77, 'Salto de Agua'), (78, 'San Cristóbal de las Casas'), (79, 'San Fernando'),
        (80, 'Siltepec'), (81, 'Simojovel'), (82, 'Sitalá'), (83, 'Socoltenango'),
        (84, 'Solosuchiapa'), (85, 'Soyaló'), (86, 'Suchiapa'), (87, 'Suchiate'),
        (88, 'Sunuapa'), (89, 'Tapachula'), (90, 'Tapalapa'), (91, 'Tapilula'),
        (92, 'Tecpatán'), (93, 'Tenejapa'), (94, 'Teopisca'), (96, 'Tila'),
        (97, 'Tonalá'), (98, 'Totolapa'), (99, 'La Trinitaria'), (100, 'Tumbalá'),
        (101, 'Tuxtla Gutiérrez'), (102, 'Tuxtla Chico'), (103, 'Tuzantán'),
        (104, 'Tzimol'), (105, 'Unión Juárez'), (106, 'Venustiano Carranza'),
        (107, 'Villa Corzo'), (108, 'Villaflores'), (109, 'Yajalón'),
        (110, 'San Lucas'), (111, 'Zinacantán'), (112, 'San Juan Cancuc'),
        (113, 'Aldama'), (114, 'Benemérito de las Américas'), (115, 'Maravilla Tenejapa'),
        (116, 'Marqués de Comillas'), (117, 'Montecristo de Guerrero'),
        (118, 'San Andrés Duraznal'), (119, 'Santiago el Pinar'),
        (120, 'Capitán Luis Ángel Vidal'), (121, 'Rincón Chamula San Pedro'),
        (122, 'El Parral'), (123, 'Emiliano Zapata'), (124, 'Mezcalapa')
    ]

    municipios_a_crear = [
        Municipio(cve_mun=cve, nom_mun=nombre)
        for cve, nombre in municipios_data
    ]

    Municipio.objects.using(db_alias).bulk_create(municipios_a_crear, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_municipio'),
    ]

    operations = [
        migrations.RunPython(populate_municipios),
    ]