# Generated by Django 4.2.24 on 2025-09-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_populate_municipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.municipio', verbose_name='Municipio'),
        ),
    ]
