# Generated by Django 4.2.24 on 2025-09-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_evento_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='municipio',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.PROTECT, to='eventos.municipio', verbose_name='Municipio'),
        ),
    ]
