# Generated by Django 4.2.24 on 2025-09-23 16:38

import django.core.validators
from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_evento_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='anotaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Anotaciones (Admin)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='archivo_respuesta_admin',
            field=models.FileField(blank=True, null=True, upload_to=eventos.models.evento_pdf_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo de Respuesta (Admin)'),
        ),
    ]
