# Generated by Django 4.2.24 on 2025-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_evento_anotaciones_evento_archivo_respuesta_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('revisado', 'Revisado'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado del Evento'),
        ),
        migrations.AlterField(
            model_name='logeventoestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('programado', 'Programado'), ('revisado', 'Revisado'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logeventoestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('programado', 'Programado'), ('revisado', 'Revisado'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
